<a href="https://colab.research.google.com/github/ItsOkDev/Project-Speech-Emotion-Recognition/blob/main/Project_Speech_Emotion_Recognition_with_librosa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


[Dataset](https://drive.google.com/drive/folders/1-dV8fAVm8mK3tQV47p5qs_DShJwxLTB8?usp=drive_link)

In [ ]:
#It will import the files which we collected
import os
Root = "/content/drive/MyDrive/Mini_Project"
os.chdir(Root)

In [ ]:
 from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
ls

'[1] Speech Emotion.pptx'
'DataBase Audio'/
 Devesh.sav
'Project Speech Emotion Recognition with librosa.ipynb'
'Test Files'/


In [ ]:
#Importing our important files to PY
import librosa
import soundfile
import os, glob, pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [ ]:
#Extract features (mfcc, chroma, mel) from a sound file
#Mel-frequency cepstral coefficients (MFCC) used characterize speakers.
#Mel-frequency is a representation of the short-term distrbution of sound

def extract_feature(file_name, mfcc, chroma, mel):
    with soundfile.SoundFile(file_name) as sound_file:
        X = sound_file.read(dtype="float32")
        sample_rate=sound_file.samplerate
        if chroma:
            stft=np.abs(librosa.stft(X))
        result=np.array([])
        if mfcc:
            mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T, axis=0)
            result=np.hstack((result, mfccs))
        if chroma:
            chroma=np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
            result=np.hstack((result, chroma))
        if mel:
            mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
            result=np.hstack((result, mel))
    return result

In [ ]:
# Emotions in the Our Drive dataset we have
emotions={
  '01':'neutral',
  '02':'calm',
  '03':'happy',
  '04':'sad',
  '05':'angry',
  '06':'fearful',
  '07':'disgust',
  '08':'surprised'
}

#Emotions to observe
observed_emotions=['calm', 'happy', 'fearful', 'disgust']

In [ ]:
#Load the data and extract features for each sound file
def load_data(test_size=0.2):
    x,y=[],[]
    for file in glob.glob("/content/drive/MyDrive/Mini_Project/DataBase Audio/Speech Emotion Recognition/Actor_*/*.wav"):
        file_name=os.path.basename(file)
        emotion=emotions[file_name.split("-")[2]]
        if emotion not in observed_emotions:
            continue
        feature=extract_feature(file, mfcc=True, chroma=True, mel=True)
        x.append(feature)
        y.append(emotion)
    return train_test_split(np.array(x), y, test_size=test_size, random_state=9)

In [ ]:
#Split the dataset
x_train, x_test, y_train, y_test=load_data(test_size=0.25)

In [ ]:
x_train

array([[-4.24843536e+02,  3.15172577e+01, -2.16740093e+01, ...,
         1.16035738e-03,  6.13754033e-04,  2.74434948e-04],
       [-5.18894653e+02,  3.56651115e+01, -1.53607740e+01, ...,
         8.55299295e-04,  5.85967093e-04,  4.50079620e-04],
       [-6.18244507e+02,  4.60745506e+01,  4.23401117e+00, ...,
         1.36048504e-04,  4.28800522e-05,  2.29466659e-05],
       ...,
       [-5.02976959e+02,  1.82096176e+01, -1.75191174e+01, ...,
         2.78437394e-03,  2.16145208e-03,  1.08908780e-03],
       [-7.71064636e+02,  3.82453308e+01,  6.00050831e+00, ...,
         6.09223298e-06,  6.10482266e-06,  3.10198266e-06],
       [-6.93767334e+02,  6.01956596e+01,  2.41615887e+01, ...,
         3.39693433e-05,  2.36386968e-05,  1.21768153e-05]])

In [ ]:
#Get the shape of the training and testing datasets
print((x_train.shape[0], x_test.shape[0]))

(354, 118)


In [ ]:
#Get the number of features extracted
print(f'Features extracted: {x_train.shape[1]}')

Features extracted: 180


In [ ]:
#Initialize the Multi Layer Perceptron Classifier
model=MLPClassifier(alpha=0.01, batch_size=256, epsilon=1e-08, hidden_layer_sizes=(300,), learning_rate='adaptive', max_iter=500)

In [ ]:
#Train the model
model.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(alpha=0.01, batch_size=256, hidden_layer_sizes=(300,),
              learning_rate='adaptive', max_iter=500)

In [ ]:
#Predict for the test set
y_pred=model.predict(x_test)

In [ ]:
y_pred

array(['happy', 'calm', 'disgust', 'calm', 'happy', 'fearful', 'happy',
       'fearful', 'calm', 'disgust', 'calm', 'disgust', 'fearful',
       'disgust', 'fearful', 'happy', 'fearful', 'fearful', 'happy',
       'disgust', 'fearful', 'happy', 'disgust', 'happy', 'disgust',
       'calm', 'happy', 'disgust', 'calm', 'disgust', 'happy', 'happy',
       'fearful', 'happy', 'happy', 'calm', 'disgust', 'happy', 'disgust',
       'fearful', 'disgust', 'fearful', 'disgust', 'happy', 'happy',
       'happy', 'happy', 'disgust', 'calm', 'disgust', 'fearful', 'happy',
       'calm', 'disgust', 'happy', 'happy', 'happy', 'calm', 'calm',
       'calm', 'fearful', 'fearful', 'disgust', 'calm', 'calm', 'calm',
       'calm', 'fearful', 'calm', 'fearful', 'happy', 'happy', 'calm',
       'calm', 'disgust', 'calm', 'happy', 'happy', 'disgust', 'happy',
       'happy', 'happy', 'fearful', 'disgust', 'calm', 'fearful',
       'fearful', 'happy', 'calm', 'disgust', 'disgust', 'disgust',
       'fearfu

In [ ]:
#Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)

#Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 75.42%


In [ ]:
from sklearn.metrics import accuracy_score, f1_score

In [ ]:
f1_score(y_test, y_pred,average=None)

array([0.88888889, 0.79310345, 0.7       , 0.77333333])

In [ ]:
import pandas as pd
df=pd.DataFrame({'Actual': y_test, 'Predicted':y_pred})
df.head(20)

Actual Predicted
0     happy     happy
1      calm      calm
2   disgust   disgust
3      calm      calm
4     happy     happy
5   fearful   fearful
6     happy     happy
7   fearful   fearful
8     happy      calm
9   disgust   disgust
10     calm      calm
11  disgust   disgust
12    happy     happy
13    happy   disgust
14    happy   fearful
15    happy     happy
16  fearful   fearful
17  fearful   fearful
18  fearful     happy
19  disgust   disgust

In [ ]:
import pickle
# Writing different model files to file
with open( 'Devesh.sav', 'wb') as f:
    pickle.dump(model,f)

In [ ]:
filename = 'Devesh.sav'
loaded_model = pickle.load(open(filename, 'rb')) # loading the model file from the storage

feature=extract_feature("/content/drive/MyDrive/Mini_Project/DataBase Audio/Speech Emotion Recognition/Actor_16/03-01-08-02-02-02-16.wav", mfcc=True, chroma=True, mel=True)

feature=feature.reshape(1,-1)

prediction=loaded_model.predict(feature)
prediction

array(['happy'], dtype='<U7')

In [ ]:
feature

array([[-5.20745178e+02,  3.20773087e+01, -1.12151184e+01,
        -1.90159589e-01, -1.38491583e+01, -1.80189419e+01,
        -1.39517689e+01, -8.85480785e+00, -7.95112705e+00,
        -1.07886896e+01, -5.70207214e+00, -6.06066656e+00,
        -3.03881907e+00, -2.44607711e+00, -1.90089658e-01,
         4.72313732e-01, -4.45844889e+00, -1.06163895e+00,
         1.61066997e+00,  1.43031865e-01, -2.08865929e+00,
         4.82732326e-01, -1.66322291e+00,  5.34366655e+00,
         2.64348149e+00,  2.50477004e+00, -1.73138455e-01,
        -1.10051191e+00, -2.25656438e+00, -9.14970517e-01,
        -7.89558232e-01, -5.30973375e-01, -1.08411610e+00,
        -4.30224895e-01,  1.14897475e-01,  1.33599627e+00,
        -1.68436304e-01,  2.06158090e+00,  1.69242501e+00,
         7.41923332e-01,  5.53748131e-01,  4.92930800e-01,
         4.61575985e-01,  4.97707605e-01,  5.46705186e-01,
         5.52395523e-01,  5.52943587e-01,  5.38808763e-01,
         5.03655076e-01,  5.16405463e-01,  5.75803757e-0